### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by r0l1** [Tyler-Hardin/thread_pool#7]
I integrated thread_pool in one of our projects and replaced the current threading mechanism.
Instead of creating new threads I wanted to reuse the threads. It was fairly easy to migrate to this lib, but I am experiencing high CPU load, when the thread pool is not used.

**Comment by r0l1** [comment]
I am using [this implementation](https://github.com/progschj/ThreadPool) now and this works just fine. Maybe this will help you.

**Comment by Tyler-Hardin** [comment]
This was essentially by design. It uses a busy loop to poll for tasks. I originally wrote the lib for one off mathematical computational projects. IIRC, throughput was higher with the busy loop, so I chose that implementation. The other lib you link to probably uses conditional variables instead. I have an old, unmaintained branch that is similar.
